Feature
kseniakap/npm-module-webbee pull request #1
Opened 2024-07-05 11:19 UTC by kseniakap

2024-07-05 12:53 UTC, Kalabass commented on src/useDocumentVisibility.tsx
> +  const [count, setCount] = useState<number>(0)
Можно не указывать тип у примитивных useState, реакт умный, сам понимает тип примитива

2024-07-05 12:56 UTC, Kalabass requested changes

2024-07-05 12:56 UTC, Kalabass commented on src/useDocumentVisibility.tsx
> +    if (document.visibilityState === 'hidden') {
имеет смысл использовать document.hidden, вместо document.visibilityState т.к там просто булевое значение, и не придётся постоянно делать проверку строк.

2024-07-05 16:02 UTC, kseniakap commented on src/useDocumentVisibility.tsx
> +  const [count, setCount] = useState<number>(0)
Окей, исправлю

2024-07-05 16:33 UTC, aidagalimova commented on test/src/components/LeaveTabCounter.tsx
> +import useDocumentVisibility  from './../../../src/useDocumentVisibility'
этот импорт ошибку возвращает
<img width="728" alt="er" src="https://github.com/kseniakap/npm-module-webbee/assets/42979243/9a3917b2-2805-4a75-ba94-0947250f1d37">

2024-07-05 16:39 UTC, kseniakap commented on test/src/components/LeaveTabCounter.tsx
> +import useDocumentVisibility  from './../../../src/useDocumentVisibility'
Исправила

2024-07-05 21:00 UTC, Kalabass approved these changes

2024-07-05 23:14 UTC, G00syara commented
Зачем нужна папка `src` в корне директорий если у тебя всё в test (но при этом в src, хук и index.ts, выглядит так будто не почистила файлы и папки) и перепиши пожалуйста запуск проекта на внешний `package.json` или допиши в `Readme` куда нужно провалиться, чтобы открыть проект, это более менее окей, но лучше исправить.
А вот что очень странно, что я должен провалиться в `test` и оттуда устанавливать зависимости и только тогда мой проект заработает, базово npm i в корне проекта должен устанавливать все нужные пакеты

2024-07-05 23:15 UTC, G00syara commented on test/src/components/LeaveTabCounter.tsx
> +// import { useDocumentVisibility } from 'webbee-use-visibility-document'
![image](https://github.com/kseniakap/npm-module-webbee/assets/95299564/5b1ea981-f167-4df8-9442-c6268f6ce8be)
Загружать пакет вот так, а не просто проект

2024-07-05 23:19 UTC, G00syara requested changes

2024-07-05 23:19 UTC, G00syara commented on test/src/components/LeaveTabCounter.tsx
> +import useDocumentVisibility from './../hooks/useDocumentVisibility'
./ лишняя
```suggestion
import useDocumentVisibility from '../hooks/useDocumentVisibility'
```

2024-07-07 12:27 UTC, sspopkov approved these changes

2024-07-07 12:27 UTC, merged